# Generated by Django 5.0.3 on 2024-05-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_mensa', models.CharField(max_length=50)),
                ('apel_mensa', models.CharField(max_length=50)),
                ('corr_mensa', models.EmailField(default='sin registro', max_length=60)),
                ('mens_mensa', models.CharField(default='sin registro', max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
