# Generated by Django 5.0.3 on 2024-06-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fecha_mensaje_fech_mensa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensaje',
        ),
    ]
