# Generated by Django 5.0.3 on 2024-07-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('docu_aspir', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('tdoc_aspir', models.CharField(max_length=45)),
                ('pnom_aspir', models.CharField(max_length=45)),
                ('snom_aspir', models.CharField(blank=True, max_length=45, null=True)),
                ('pape_aspir', models.CharField(max_length=45)),
                ('sape_aspir', models.CharField(max_length=45)),
                ('gene_aspir', models.CharField(max_length=45)),
                ('pais_aspir', models.CharField(max_length=80)),
                ('fech_aspir', models.DateField()),
                ('corr_aspir', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'aspirante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('nume_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('curs_ficha', models.IntegerField()),
                ('inic_ficha', models.DateField()),
                ('fina_ficha', models.DateField()),
                ('luga_ficha', models.CharField(max_length=60)),
                ('nota_ficha', models.CharField(max_length=300)),
                ('ficha_activa', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaAspirante',
            fields=[
                ('iden_ficha_aspirante', models.AutoField(primary_key=True, serialize=False)),
                ('nive_aspir', models.CharField(max_length=100)),
                ('area_aspir', models.CharField(max_length=100)),
                ('carg_aspir', models.CharField(max_length=100)),
                ('empl_aspir', models.CharField(max_length=100)),
                ('arl_aspir', models.CharField(max_length=100)),
                ('sect_aspir', models.CharField(max_length=100)),
                ('doc1', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc2', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc3', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc4', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc5', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc6', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc7', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc8', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc9', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc10', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc11', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'db_table': 'ficha_aspirante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('iden_instr', models.IntegerField(primary_key=True, serialize=False)),
                ('nomb_instr', models.CharField(max_length=60)),
                ('corr_instr', models.CharField(max_length=65)),
                ('ciud_instr', models.CharField(blank=True, max_length=45, null=True)),
                ('tele_instr', models.CharField(blank=True, max_length=45, null=True)),
                ('resu_instr', models.CharField(blank=True, max_length=500, null=True)),
                ('carg_instr', models.CharField(blank=True, max_length=45, null=True)),
                ('cent_instr', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_instr', models.ImageField(upload_to='instructor/')),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('iden_mensa', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_mensa', models.CharField(max_length=60)),
                ('apel_mensa', models.CharField(max_length=60)),
                ('corr_mensa', models.CharField(max_length=60)),
                ('mens_mensa', models.CharField(max_length=500)),
                ('fech_mensa', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'mensaje',
                'managed': False,
            },
        ),
    ]
